export const $input = document.querySelector<HTMLInputElement>('#email')
export const $checkIcon = document.querySelector<SVGAElement>('#check-icon')
export const $contactForm = document.querySelector<HTMLDivElement>('#contact-form')
export const $contactButton = document.querySelector<HTMLButtonElement>('#we-contact-you')
export const $positiveMessage = document.querySelector<HTMLDivElement>('#positive-message')
